name: marp-cli-carroarmato0 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.16.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A CLI interface for Marp and Marpit based converters
description: |
  A CLI interface, for Marp (using @marp-team/marp-core) and any slide deck converter based on Marpit framework.
  It can convert Marp / Marpit Markdown files into static HTML / CSS, PDF, PowerPoint document, and image(s) easily.

  https://github.com/marp-team/marp-cli

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  marp:
    command: marp
    plugs:
      - home
      - network
      - network-bind

parts:
  marp-cli:
    source: https://github.com/marp-team/marp-cli/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/marp-cli-v${SNAPCRAFT_PROJECT_VERSION}-linux.tar.gz
    plugin: dump
